### ISSUE TITLE
how openload generate url 

### ISSUE THREAD

**Issue by reguez** [khanghoang/openload-player#1]
hey dude can you explain to me what javascript function is executing when the user tries to watch the video on openload ? Im trying to make c# code to generate that url

**Comment by khanghoang** [comment]
@reguez you can try to parse this lines of code into any openload video page

```
var directURL = player.src({
  type: vt,
  src: vs
}).K.src;
```

Then looking for a `video` html tag, you will find the src link

**Comment by khanghoang** [comment]
@reguez i will close this issue, feel free to re-open it if you need
